ddproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from delivery import views as d_views
from service import views as s_views
from postman import views as pm_views
from pcenter import views as pc_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', d_views.index, name="home"), 
    url(r'^login/$', d_views.d_login, name="login"), 
    url(r'^logout/$', d_views.d_logout, name="logout"), 
    url(r'^register/$', d_views.register, name="register"), 
    url(r'^new_order/$', d_views.new_order, name="new_order"), 
    url(r'^order_view/(?P<pk>\d{0,50})/$', d_views.order_review, name="order_review"), 
    url(r'^order_list/$', d_views.order_list, name="order_list"), 
    url(r'^order_confirm/(?P<oid>\d{0,50})/(?P<uid>\d{0,50})/$', d_views.order_confirm, name="order_confirm"), 
    url(r'^order_track/(?P<oid>\d{0,50})/$', d_views.order_track, name="order_track"), 
    url(r'^service_autocomplete/$', s_views.service_autocomplete, name="service_autocomplete"), 

    url(r'^postman/add_order/$', pm_views.register_order, name="postman_register_order"), 
    url(r'^postman/order_list/$', pm_views.order_list, name="postman_order_list"), 
    url(r'^postman/order/next/$', pm_views.order_next, name="postman_order_next"), 
    url(r'^postman/order/next_bulk/$', pm_views.order_next_bulk, name="postman_order_next_bulk"), 
    url(r'^postman/order/confirm/$', pm_views.confirm_order, name="postman_order_confirm"), 
    url(r'^postman/order/confirm_bulk/$', pm_views.confirm_order_bulk, name="postman_order_confirm_bulk"), 

    url(r'^pcenter/order_list/$', pc_views.order_list, name="pcenter_order_list"), 
    url(r'^pcenter/add_order/$', pc_views.register_order, name="pcenter_register_order"), 
    url(r'^pcenter/order/next/$', pc_views.order_next, name="pcenter_order_next"), 
    url(r'^pcenter/order/next_bulk/$', pc_views.order_next_bulk, name="pcenter_order_next_bulk"), 
    url(r'^pcenter/order/confirm/$', pc_views.confirm_order, name="pcenter_order_confirm"), 
    url(r'^pcenter/order/confirm_bulk/$', pc_views.confirm_order_bulk, name="pcenter_order_confirm_bulk")

]

service/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from service import models

import json

# Create your views here.

@login_required
def service_autocomplete(request):
	if request.method == "GET":
		return HttpResponse("POST only")

	s_id = int(request.POST.get('service_id'))
	keyword = request.POST.get('keyword')
	field_here = request.POST.get('field')
	all_data = request.POST.get('all')

	service = models.Service.objects.get(pk=s_id)
	service_data = service.data
	field_data = service.fields

	target_field = {}

	loc_fields = []
	for field in field_data:
		if field['location'] == True:
			loc_fields.append(field)
		if field['v_name'] == field_here:
			target_field = field

	location_data = models.SupportedLocation.objects.filter(service = service)
	if len(location_data) != 0:
		location_data = location_data[0].locations
	else:
		location_data = []

	result = {}

	result[service.itemName] = []

	for item in service_data:
		if str(item[target_field['v_name']]).find(keyword) != -1:
			result[service.itemName].append(item)
			if all_data == 'true':
				for location in location_data:
					# location = location_data[lid]
					yes = True
					for loc_field in loc_fields:
						# loc_field = loc_fields[fid]
						if location[loc_field['v_name']] != item[loc_field['v_name']]:
							yes = False
							break
					if yes:
						result['location'] = location
						break

	return HttpResponse(json.dumps(result))

templates/widgets/data.html
<br/>

<label> {{ name|title }} </label> <br/>

<div class="data">
<table> 
	<thead>
		<tr id="data-headers" > </tr>
	</thead>
	<tbody id="data-content">
	</tbody>
</table>
</div>

<input type="hidden" name="{{name}}" id="data-submit" value="" />

<script language="javascript">
	$(document).ready(function() {
		var data = JSON.parse('{{js_string}}');

		$("#data-submit").val(JSON.stringify(data)); 

		function refresh_data_table() {

			$("#data-headers").html('');
			$("#data-content").html('');

			var fields = JSON.parse($("#field-submit").val()); 

			for(idx in fields) {
				field = fields[idx]
				var elem = '<th class="'+field['name']+'">'+capitalizeFirstLetter(field['name']) + '</th>';
				$("#data-headers").append(elem);
			}
			$("#data-headers").append('<th> - </th>')

			for(idx in data) {
				item = data[idx];
				var elem = '<tr>';
				for(fid in fields) {
					elem = elem + '<td>'; 
					field = fields[fid]
					if(field['type'] == 'select') {
						elem = elem + '<select row="'+idx+'" column = "'+field['v_name']+'" class="value-data select" >'
						values = [];
						if(field['value'] != undefined) {
							values = field['value'].split(',');
						} else {
							values = []
						}
						for(val in values) {
							selected = '';
							if(values[val] == item[field['v_name']])
								selected = 'selected';
							elem = elem + '<option value="'+values[val]+'" '+selected+'>'+capitalizeFirstLetter(values[val])+'</option>';
						}
						elem = elem + '</select>';
					} else {
						checked = ''
						val = item[field['v_name']]
						if(field['type'] == 'checkbox') {
							if(item[field['v_name']] == true) {
								checked = 'checked'
								val = true;
							} else {
								val = false;
							}
						}
						elem = elem + '<input type="'+field['type']+'" row="'+idx+'" column = "'+field['v_name']+'" value="'+val+'" class="value-data '+field['type']+'" id="'+idx+fid+'" '+checked+' />';
						if(field['type'] == 'checkbox') 
							elem = elem + '<label for="'+idx+fid+'"> -</label>';
						
					}
					elem = elem +'</td>';
				}
				elem = elem + '<td> <span row="'+idx+'" class="btn btn-floating btn-small waves-effect waves-light red darken-4 z-depth-1 remove-row-data"> <i class="material-icons">delete</i> </span> </td>';
				elem = elem + '</tr>';
				$("#data-content").append(elem);
			}
			var button = '<tr> <td> <span class="btn btn-default waves-effect waves-light z-depth-2" id="add-data"> <i class="material-icons"> add </i> </span> </td> </tr>';
			$("#data-content").append(button);

			$("select.select").material_select();

			// Action attachement
			$(".value-data").change(function() {
				var row = $(this).attr('row');
				var col = $(this).attr('column');
				data[row][col] = $(this).val();
				if($(this).hasClass('checkbox'))
					data[row][col] = !eval(data[row][col]);
				refresh_data_table();
			}); 
			$(".remove-row-data").click(function() {
				var row = $(this).attr('row');
				data.splice(row, 1);
				refresh_data_table();
			}); 
			$("#add-data").click(function() {
				var item = {};
				for(fid in fields) {
					field = fields[fid];
					item[field['v_name']] = '';
				}
				data.push(item);
				refresh_data_table();
			}); 

			$("#data-submit").val(JSON.stringify(data)); 
		}

		refresh_data_table();

		$("#field-submit").change(function() {
			refresh_data_table();
		}); 

	}); 
</script>

templates/widgets/field.html
<br/>
<label> {{ name|title }} </label> <br />

<div class="fields">
<table> 
	<thead>
		<tr id="field-headers" > </tr>
	</thead>
	<tbody id="field-content">

	</tbody>
</table>
</div>

<input type="hidden" name="{{name}}" id="field-submit" value="" />

<script language="javascript">
	function capitalizeFirstLetter(string) {
		return string.charAt(0).toUpperCase() + string.slice(1);
	}

	$(document).ready(function() {
		var data = JSON.parse('{{js_string}}');
		var fields = JSON.parse('{{fields}}');

		for(idx in fields) {
			field = fields[idx]
			var elem = '<th class="'+field['name']+'">'+capitalizeFirstLetter(field['name']) + '</th>';
			$("#field-headers").append(elem);
		}
		$("#field-headers").append('<th> - </th>')

		function refresh_field_table() {
			$("#field-content").html('');
			for(idx in data) {
				item = data[idx];
				var elem = '<tr>';
				for(fid in fields) {
					elem = elem + '<td>'; 
					field = fields[fid]
					if(field['type'] == 'select') {
						elem = elem + '<select row="'+idx+'" column = "'+field['name']+'" class="value select" >'
						for(val in field['value']) {
							selected = '';
							if(field['value'][val] == item['type'])
								selected = 'selected';
							elem = elem + '<option value="'+field['value'][val]+'" '+selected+'>'+capitalizeFirstLetter(field['value'][val])+'</option>';
						}
						elem = elem + '</select>';
					} else {
						checked = ''
						val = item[field['name']]
						if(field['type'] == 'checkbox') {
							if(item[field['name']] == true) {
								checked = 'checked'
								val = true;
							} else {
								val = false;
							}
						}
						elem = elem + '<input type="'+field['type']+'" row="'+idx+'" column = "'+field['name']+'" value="'+val+'" class="value '+field['type']+'"  id="'+idx+fid+'-field" '+checked+' />';
						if(field['type'] == 'checkbox') 
							elem = elem + '<label for="'+idx+fid+'-field"> -</label>';
					}
					elem = elem +'</td>';
				}
				elem = elem + '<td> <span row="'+idx+'" class="btn btn-floating btn-small waves-effect waves-light red darken-4 z-depth-1 remove-row"> <i class="material-icons">delete</i> </span> </td>';
				elem = elem + '</tr>';
				$("#field-content").append(elem);
			}
			var button = '<tr> <td> <span class="btn btn-default waves-effect waves-light z-depth-2" id="add-field"> <i class="material-icons"> add </i> </span> </td> </tr>';
			$("#field-content").append(button);

			$("select.select").material_select();

			// Action attachement
			$(".value").change(function() {
				var row = $(this).attr('row');
				var col = $(this).attr('column');
				data[row][col] = $(this).val();
				if($(this).attr('column') == 'name')
					data[row]['v_name'] = $(this).val().toLowerCase().replace(/\s/g,'_').replace(/\//g,'');
				if($(this).hasClass('checkbox'))
					data[row][col] = !eval(data[row][col]);
				refresh_field_table();
			}); 
			$(".remove-row").click(function() {
				var row = $(this).attr('row');
				data.splice(row, 1);
				refresh_field_table();
			}); 
			$("#add-field").click(function() {
				var item = {};
				for(fid in fields) {
					field = fields[fid];
					item[field['name']] = '';
					item['v_name'] = '';
				}
				item['type'] = 'text';
				data.push(item);
				refresh_field_table();
			}); 
			$("#field-submit").val(JSON.stringify(data)); 
			// refresh_data_table(); // Reference to function in  'data.html' 
			$("#field-submit").change();
		}

		refresh_field_table();

	}); 
</script>

templates/widgets/location.html
<label> {{ name|title }} </label> <br/>

<div class="location">
<table> 
	<thead>
		<tr id="location-headers" > </tr>
	</thead>
	<tbody id="location-content">
	</tbody>
</table>
</div>

<input type="hidden" name="{{name}}" id="location-submit" value="" />

<script language="javascript">
	function capitalizeFirstLetter(string) {
		return string.charAt(0).toUpperCase() + string.slice(1);
	}

	$(document).ready(function() {
		var data = JSON.parse('{{js_string}}');
		var loc_fields = JSON.parse('{{loc_fields}}'); 
		var fields = JSON.parse('{{fields}}'); 
		var countries = JSON.parse('{{countries}}')

		$("#location-submit").val(JSON.stringify(data)); 

		function refresh_location_data(s_id) {
			for(idx in loc_fields[s_id]) {
				field = loc_fields[s_id][idx];
				var elem = '<th class="'+field['v_name']+'">'+capitalizeFirstLetter(field['name'] ) + '</th>';
				$("#location-headers").append(elem);
			}
			for(idx in fields) {
				field = fields[idx]
				var elem = '<th class="'+field+'">'+capitalizeFirstLetter(field) + '</th>';
				$("#location-headers").append(elem);
			}
			$("#location-headers").append('<th> - </th>')

			$("#location-content").html('');
			for(didx in data) {
				item = data[didx];
				var elem = '<tr>'
				for(fid in loc_fields[s_id]) {
					elem = elem + '<td>'
					field = loc_fields[s_id][fid];
					if(field['type'] == 'select') {
						elem = elem + '<select row="'+didx+'" column = "'+field['v_name']+'" class="value-location select" >'
						values = [];
						if(field['value'] != undefined) {
							values = field['value'].split(',');
						} else {
							values = []
						}
						for(val in values) {
							selected = '';
							if(values[val] == item[field['v_name']])
								selected = 'selected';
							elem = elem + '<option value="'+values[val]+'" '+selected+'>'+capitalizeFirstLetter(values[val])+'</option>';
						}
						elem = elem + '</select>';
					} else {
						checked = ''
						val = item[field['v_name']]
						if(field['type'] == 'checkbox') {
							if(item[field['v_name']] == true) {
								checked = 'checked'
								val = true;
							} else {
								val = false;
							}
						}
						elem = elem + '<input type="'+field['type']+'" row="'+didx+'" column = "'+field['v_name']+'" value="'+val+'" class="value-location '+field['type']+'" id="'+didx+fid+'" '+checked+' />';
						// elem = elem + '<label for="'+didx+fid+'"> -</label>';
					}
					elem = elem +'</td>';
				}
				for(idx in fields) {
					field = fields[idx]
					elem = elem + '<td>';
					if(field == 'country') {
						elem = elem + '<select row="'+didx+'" column="'+field+'" class="select value-location">'
						for(val in countries) {
							selected = '';
							if(item[field] == val)
								selected = 'selected';
							elem = elem + '<option value="'+val+'" '+selected+'> '+countries[val]+' </option>';
						}
						elem = elem + '</select>';
					} else {
						elem = elem + '<input type="text" row="'+didx+'" column="'+field+'" value="'+item[field]+'" class="value-location" />'
					}
					elem = elem + '</td>';
				}
				elem = elem + '<td> <span row="'+didx+'" class="btn btn-floating btn-small waves-effect waves-light red darken-4 z-depth-1 remove-row-location"> <i class="material-icons">delete</i> </span> </td>';
				elem = elem + '</tr>';
				$("#location-content").append(elem);
			}
			var button = '<tr> <td> <span class="btn btn-default waves-effect waves-light z-depth-2" id="add-location"> <i class="material-icons"> add </i> </span> </td> </tr>';
			$("#location-content").append(button);

			$("select.select").material_select();


			$("#add-location").click(function() {
				var item = {};
				console.log(loc_fields[s_id]);
				for(idx in loc_fields[s_id]) {
					field = loc_fields[s_id][idx];
					item[field['v_name']] = ''
				}
				for(idx in fields) {
					field = fields[idx]
					item[field] = '';
				}
				data.push(item);
				$("#id_service").change();
			}); 

			$(".remove-row-location").click(function() {
				var row = $(this).attr('row');
				data.splice(row, 1);
				$("#id_service").change();
			}); 

			$(".value-location").change(function() {
				var row = $(this).attr('row');
				var col = $(this).attr('column');
				data[row][col] = $(this).val();
				$("#id_service").change();
			}); 

			$("#location-submit").val(JSON.stringify(data));
		}

		$("#id_service").change(function() {
			$("#location-headers").html('');
			var s_id = $(this).val();
			refresh_location_data(s_id);
		}); 

		$("#id_service").change();

	}); 
</script>